// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by app_intents_codegen
// Run `dart run app_intents_codegen:generate_swift` to regenerate

import AppIntents
import UIKit

@available(iOS 16.0, *)
struct CompleteTaskIntentSpec: AppIntent {
    static var title: LocalizedStringResource = "Complete Task"
    static var description: IntentDescription =
        IntentDescription("Mark a task as completed")

    static var openAppWhenRun: Bool { true }

    @Parameter(title: "Task ID", description: "The ID of the task to complete")
    var taskId: String

    @MainActor
    func perform() async throws -> some IntentResult {
        var components = URLComponents()
        components.scheme = "taskapp"
        components.host = "complete"

        var queryItems = [URLQueryItem]()
        queryItems.append(URLQueryItem(name: "taskId", value: String(describing: taskId)))

        if !queryItems.isEmpty {
            components.queryItems = queryItems
        }

        guard let url = components.url else {
            return .result()
        }

        await UIApplication.shared.open(url)
        return .result()
    }
}

@available(iOS 16.0, *)
struct CreateTaskIntentSpec: AppIntent {
    static var title: LocalizedStringResource = "Create Task"
    static var description: IntentDescription =
        IntentDescription("Create a new task in your task list")

    static var openAppWhenRun: Bool { true }

    @Parameter(title: "Title", description: "The title of the task")
    var title: String
    @Parameter(title: "Description", description: "Optional description for the task")
    var description: String?
    @Parameter(title: "Due Date", description: "When the task is due")
    var dueDate: Date?

    @MainActor
    func perform() async throws -> some IntentResult {
        var components = URLComponents()
        components.scheme = "taskapp"
        components.host = "create"

        var queryItems = [URLQueryItem]()
        queryItems.append(URLQueryItem(name: "title", value: String(describing: title)))
        if let description {
            queryItems.append(URLQueryItem(name: "description", value: String(describing: description)))
        }
        if let dueDate {
            queryItems.append(URLQueryItem(name: "dueDate", value: ISO8601DateFormatter().string(from: dueDate)))
        }

        if !queryItems.isEmpty {
            components.queryItems = queryItems
        }

        guard let url = components.url else {
            return .result()
        }

        await UIApplication.shared.open(url)
        return .result()
    }
}

@available(iOS 16.0, *)
struct TaskEntitySpec: AppEntity {
    static var typeDisplayRepresentation: TypeDisplayRepresentation =
        TypeDisplayRepresentation(name: "Task")

    static var defaultQuery = TaskEntitySpecQuery()

    var id: String
    var title: String
    var description: String?

    var displayRepresentation: DisplayRepresentation {
        DisplayRepresentation(title: "\(title)", subtitle: "\(description ?? "")")
    }
}

@available(iOS 16.0, *)
struct TaskEntitySpecQuery: EntityQuery {
    func entities(for identifiers: [String]) async throws -> [TaskEntitySpec] {
        // TODO: Implement entity fetching via FlutterBridge
        return []
    }
}

