// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by app_intents_codegen
// Run `dart run app_intents_codegen:generate_swift` to regenerate

import AppIntents
import UIKit

// MARK: - URL Scheme Helper

@available(iOS 16.0, *)
private enum AppIntentURLHelper {
    static let scheme = "taskapp"

    static func openURL(_ urlString: String) async throws {
        guard let url = URL(string: urlString) else {
            throw AppIntentError.custom(code: "INVALID_URL", message: "Failed to create URL")
        }

        await MainActor.run {
            UIApplication.shared.open(url, options: [:], completionHandler: nil)
        }
    }

    static func encodeParam(_ value: String) -> String {
        return value.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? value
    }
}

// MARK: - App Intents

@available(iOS 16.0, *)
struct CompleteTaskIntentSpec: AppIntent {
    static var title: LocalizedStringResource = "Complete Task"
    static var description: IntentDescription =
        IntentDescription("Mark a task as completed")

    static var openAppWhenRun: Bool = true

    @Parameter(title: "Task")
    var task: TaskEntitySpec

    @MainActor
    func perform() async throws -> some IntentResult {
        // Open app with URL scheme to complete task
        let urlString = "\(AppIntentURLHelper.scheme)://complete?taskId=\(AppIntentURLHelper.encodeParam(task.id))"
        try await AppIntentURLHelper.openURL(urlString)
        return .result()
    }
}

@available(iOS 16.0, *)
struct CreateTaskIntentSpec: AppIntent {
    static var title: LocalizedStringResource = "Create Task"
    static var description: IntentDescription =
        IntentDescription("Create a new task in your task list")

    static var openAppWhenRun: Bool = true

    @Parameter(title: "Title", description: "The title of the task")
    var title: String
    @Parameter(title: "Description", description: "Optional description for the task")
    var description: String?
    @Parameter(title: "Due Date", description: "When the task is due")
    var dueDate: Date?

    @MainActor
    func perform() async throws -> some IntentResult {
        // Build URL with parameters
        var urlString = "\(AppIntentURLHelper.scheme)://create?title=\(AppIntentURLHelper.encodeParam(title))"

        if let desc = description {
            urlString += "&description=\(AppIntentURLHelper.encodeParam(desc))"
        }

        if let date = dueDate {
            let dateString = ISO8601DateFormatter().string(from: date)
            urlString += "&dueDate=\(AppIntentURLHelper.encodeParam(dateString))"
        }

        try await AppIntentURLHelper.openURL(urlString)
        return .result()
    }
}

@available(iOS 16.0, *)
struct TaskEntitySpec: AppEntity {
    static var typeDisplayRepresentation: TypeDisplayRepresentation =
        TypeDisplayRepresentation(name: "Task")

    static var defaultQuery = TaskEntitySpecQuery()

    var id: String
    var title: String
    var description: String?

    var displayRepresentation: DisplayRepresentation {
        DisplayRepresentation(title: "\(title)", subtitle: "\(description ?? "")")
    }
}

@available(iOS 16.0, *)
struct TaskEntitySpecQuery: EntityQuery {
    private static let entityIdentifier = "com.example.taskapp.TaskEntity"

    func entities(for identifiers: [String]) async throws -> [TaskEntitySpec] {
        let result = try await FlutterBridge.shared.queryEntities(
            entityIdentifier: Self.entityIdentifier,
            identifiers: identifiers
        )

        return result.compactMap { json in
            guard let id = json["id"] as? String,
                  let title = json["title"] as? String else { return nil }
            return TaskEntitySpec(
                id: id,
                title: title,
                description: json["description"] as? String
            )
        }
    }

    func suggestedEntities() async throws -> [TaskEntitySpec] {
        let result = try await FlutterBridge.shared.suggestedEntities(
            entityIdentifier: Self.entityIdentifier
        )

        return result.compactMap { json in
            guard let id = json["id"] as? String,
                  let title = json["title"] as? String else { return nil }
            return TaskEntitySpec(
                id: id,
                title: title,
                description: json["description"] as? String
            )
        }
    }
}

