builders:
  app_intents_builder:
    import: "package:app_intents_codegen/builder.dart"
    builder_factories: ["appIntentsBuilder"]
    build_extensions: {".dart": [".intent.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      app_intents_codegen|app_intents_builder:
        enabled: true
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - lib/**/*.g.dart
            - lib/**/*.intent.dart
