// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by app_intents_codegen
// Run `dart run app_intents_codegen:generate_widget_swift` to regenerate
//
// Add this file to the Widget Extension target ONLY. Including the same
// App Intent type in both the app target and an extension target duplicates
// it in Metadata.appIntents and breaks intent resolution.

import AppIntents
import AppIntentsBridge

/// App Group storage the generated widget queries read.
///
/// These values are baked in at generation time from the `--app-group` and
/// `--storage-identifier` options. The storage identifier is the **main app's**
/// bundle identifier (or the explicit `storageIdentifier` passed to
/// `AppIntentsPlugin.configure`) — this extension's own bundle identifier is
/// different and would read the wrong key.
enum GeneratedWidgetEntityCache {
    static let appGroupIdentifier = "group.com.example.app"
    static let storageIdentifier = "com.example.app"

    static var cache: AppIntentsEntityCache {
        AppIntentsEntityCache(
            appGroupIdentifier: appGroupIdentifier,
            storageIdentifier: storageIdentifier
        )
    }
}

/// Widget Extension entity for `TaskEntitySpec`.
///
/// Backed by the App Group entity cache — see GeneratedWidgetEntityCache.
@available(iOS 17.0, *)
struct TaskEntitySpecWidgetEntity: AppEntity {
    static var typeDisplayRepresentation: TypeDisplayRepresentation =
        TypeDisplayRepresentation(name: "Task")

    static var defaultQuery = TaskEntitySpecWidgetQuery()

    var id: String
    var title: String
    var description: String?
    var iconName: String?

    var displayRepresentation: DisplayRepresentation {
        if let iconName {
            return DisplayRepresentation(title: "\(title)", subtitle: "\(description ?? "")", image: .init(systemName: iconName))
        }
        return DisplayRepresentation(title: "\(title)", subtitle: "\(description ?? "")")
    }
}

/// Reads `TaskEntitySpec` values from the App Group
/// cache the host app persists.
@available(iOS 17.0, *)
struct TaskEntitySpecWidgetQuery: EnumerableEntityQuery {
    /// App Group cache key written from Dart via setCachedValue.
    static let cacheKey = "com.example.taskapp.cache.tasks"

    func allEntities() async throws -> [TaskEntitySpecWidgetEntity] {
        Self.cachedEntities()
    }

    func entities(for identifiers: [String]) async throws -> [TaskEntitySpecWidgetEntity] {
        let all = Self.cachedEntities()
        return identifiers.compactMap { identifier in
            all.first { $0.id == identifier }
        }
    }

    /// Reads the persisted entity list from App Group UserDefaults.
    /// Returns an empty list when the host app has not written the
    /// cache yet, or when the App Group is not reachable.
    private static func cachedEntities() -> [TaskEntitySpecWidgetEntity] {
        GeneratedWidgetEntityCache.cache
            .entities(
                forCacheKey: cacheKey,
                idKey: "id",
                titleKey: "title",
                subtitleKey: "description",
                imageKey: "iconName"
            )
            .map { cached in
                TaskEntitySpecWidgetEntity(
                    id: cached.id,
                    title: cached.title,
                    description: cached.subtitle,
                    iconName: cached.imageName
                )
            }
    }
}

/// Widget configuration intent for the widget's
/// "long-press → Edit Widget" sheet.
@available(iOS 17.0, *)
struct SelectTaskWidgetConfig: WidgetConfigurationIntent {
    static var title: LocalizedStringResource = "Displayed task"
    static var description: IntentDescription = IntentDescription("Choose which task this widget shows.")
    static var isDiscoverable: Bool { false }

    /// Stable across builds: changing it invalidates existing
    /// widget configurations.
    static var persistentIdentifier: String { "com.example.taskapp.selectTask" }

    @Parameter(title: "Task", description: "The task to display")
    var task: TaskEntitySpecWidgetEntity?

    @Parameter(title: "Show completed")
    var showCompleted: Bool
}
