#!/usr/bin/env bash
# Verifies that the WWDC26 experimental Swift output actually compiles against
# the beta iOS SDK — the load-bearing check that golden/unit tests cannot do
# (they only assert the emitted strings).
#
# It type-checks the generated Swift TWICE: once with `-D APP_INTENTS_WWDC26`
# (the WWDC26 form) and once without (the stable `#else` fallback). Both must
# pass: a project that enables experimental codegen but hasn't set the build
# flag must still get compiling stable Swift.
#
# Run it against BOTH Xcodes. With the iOS 27 SDK it checks both branches. With
# an older SDK it checks only the stable branch — the WWDC26 branch cannot
# compile there by design, but everything outside `#if` must, which is what
# catches a feature that graduated out of the gate too early (#51).
#
# Usage: scripts/verify_experimental_swift.sh
#        DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
#          scripts/verify_experimental_swift.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CODEGEN="$REPO_ROOT/packages/app_intents_codegen"
BRIDGE="$REPO_ROOT/packages/app_intents/ios/app_intents/Sources/AppIntentsBridge"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
GEN="$WORK/GeneratedExperimental.swift"
MOD="$WORK/mod"
mkdir -p "$MOD"

# Pick an iOS Simulator SDK (no codesigning needed) but compile at the PLUGIN'S
# MINIMUM deployment target, not the SDK's own version. Compiling at the SDK
# version silently satisfies every `@available` in the generated code, so a
# newer-than-declared API used without a guard type-checks fine there and only
# fails in a real app. At iOS 17.0 it fails here, which is the point.
SDK="$(xcodebuild -showsdks 2>/dev/null | sed -n 's/.*-sdk \(iphonesimulator[0-9.]*\).*/\1/p' | tail -1)"
SDK_VER="${SDK#iphonesimulator}"
DEPLOYMENT_TARGET="17.0"
TARGET="arm64-apple-ios${DEPLOYMENT_TARGET}-simulator"

echo "==> Xcode: $(xcodebuild -version | head -1) (SDK: $SDK, deployment target: iOS $DEPLOYMENT_TARGET)"

echo "==> Emitting experimental Swift"
( cd "$CODEGEN" && dart run tool/emit_experimental_swift.dart "$GEN" >/dev/null )

echo "==> Building AppIntentsBridge module"
xcrun --sdk "$SDK" swiftc -target "$TARGET" -emit-module -module-name AppIntentsBridge \
  -emit-module-path "$MOD/AppIntentsBridge.swiftmodule" \
  "$BRIDGE"/*.swift

# The real `app_intents` module imports Flutter, which is not available here, so
# an entity with a cache key (any `indexed`/`enumerable`/`persistedCacheKey`
# one) could not be type-checked at all. This stub carries only the surface the
# generated Swift touches. Keep it in step with AppIntentsPlugin — a signature
# change there that is not mirrored here would let broken output pass.
cat > "$WORK/app_intents_stub.swift" <<'SWIFT'
import Foundation

public class AppIntentsPlugin {
    public static func getCached(forKey key: String) -> Any? { nil }
    public static func setPendingAction(identifier: String, params: [String: Any]) {}
}
SWIFT
echo "==> Building app_intents stub module"
xcrun --sdk "$SDK" swiftc -target "$TARGET" -emit-module -module-name app_intents \
  -emit-module-path "$MOD/app_intents.swiftmodule" \
  "$WORK/app_intents_stub.swift"

typecheck() {
  local label="$1"; shift
  echo "==> typecheck: $label"
  if xcrun --sdk "$SDK" swiftc -typecheck -target "$TARGET" -I "$MOD" "$@" "$GEN"; then
    echo "    OK"
  else
    echo "    FAILED ($label)" >&2
    exit 1
  fi
}

typecheck "stable fallback (no -D APP_INTENTS_WWDC26)"

# The Widget Extension output is generated by a different CLI into the example
# app, and nothing else compiles it — a `swiftc` run here is the only thing
# standing between a broken emitter and an Xcode build.
WIDGET="$REPO_ROOT/app/ios/TaskWidget/GeneratedIntents/GeneratedWidgetIntents.swift"
if [ -f "$WIDGET" ]; then
  echo "==> typecheck: generated Widget Extension Swift"
  if xcrun --sdk "$SDK" swiftc -typecheck -target "$TARGET" -I "$MOD" "$WIDGET"; then
    echo "    OK"
  else
    echo "    FAILED (widget extension output)" >&2
    exit 1
  fi
fi

# The WWDC26 branch names iOS 27 symbols that are absent from earlier SDKs, so
# only check it when the SDK can actually provide them.
if [ "${SDK_VER%%.*}" -ge 27 ]; then
  typecheck "WWDC26 form (-D APP_INTENTS_WWDC26)" -D APP_INTENTS_WWDC26
  echo "==> All experimental Swift type-checks passed (both branches)."
else
  echo "==> Stable branch passed. Skipped the WWDC26 branch: SDK $SDK_VER has no"
  echo "    iOS 27 symbols. Re-run with DEVELOPER_DIR pointing at an Xcode 27."
fi
